options(stringsAsFactors = F)
pacman::p_load(optparse,glue,dplyr,ggplot2,lessR,purrr)
import::from(tidyr,unite,separate,gather,spread)
import::from(magrittr,set_colnames,set_rownames,"%<>%")
import::from(zeallot,"%<-%")
import::from(tibble,column_to_rownames,rownames_to_column)
import::from(parallel,detectCores)
import::from(data.table,fread,fwrite)
import::from(wrMisc,rowGrpMeans)
import::from("~/earlyChromMM/utils/Basics.R",dirC,unilen,list2flat,tablem,TODsave,grpmean,matNorm)

